#@ load("@ytt:data", "data")
---
image:
  repository: #@ data.values.repo + "/grafana/grafana"
  tag: 7.5.2
  pullSecrets:
  - #@ data.values.pullsecret

testFramework:
  image: #@ data.values.repo + "/bats/bats"
  tag: "v1.1.0"


downloadDashboardsImage:
  repository: #@ data.values.repo + "/curlimages/curl"
  tag: 7.73.0

initChownData:
  image:
    repository: #@ data.values.repo + "/busybox"
    tag: "1.31.1"

sidecar:
  image:
    repository: #@ data.values.repo + "/kiwigrid/k8s-sidecar"
    tag: 1.10.7

imageRenderer:
  image:
    repository: #@ data.values.repo + "/grafana/grafana-image-renderer"